# Generated by Django 3.1 on 2020-08-17 13:34

from django.db import migrations, models

from moonvision.image_classification import models as image_classification_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_classification_models.image_upload)),
                ('model_type', models.CharField(max_length=255)),
                ('image_label', models.CharField(max_length=255, blank=True)),
            ],
        ),
    ]
